encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path('wiki/<str:name>', views.entry_page, name='entry_page'),
    path("search", views.search, name="search"),
    path("new", views.new_page, name="new_page"),
    path('edit/<str:entry>', views.edit_page, name='edit_page'),
    path('random', views.random_page, name='random_page')
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse

import markdown2
import random

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def entry_page(request, name):
    mkdown = util.get_entry(name)

    if not mkdown:
        raise Http404('The requested page was not found.')

    html = markdown2.markdown(mkdown)

    # return render(request, f'encyclopedia/{name}.html', {"name": name})
    return render(request, 'encyclopedia/entry.html', {"html": html, 'entry': name})


def search(request):
    query = util.get_entry(request.GET['q'])

    if query:
        html = markdown2.markdown(query)
        return render(request, 'encyclopedia/entry.html', {"html": html})

    entries = util.list_entries()
    # print(entries)
    results = []

    for entry in entries:
        if request.GET['q'].lower() in entry.lower():
            results.append(entry)

    return render(request, "encyclopedia/search.html", {'results': results, 'number': len(results), 'q': request.GET['q']})


def new_page(request):
    if request.method == 'POST':
        # print(request.POST)
        title = request.POST.get('title', '').strip()
        content = request.POST.get('content', '').strip()

        if not title or not content:
            error = "Error. Title and content are required fields."
            return render(request, "encyclopedia/new_page.html", {'error': error, 'title': title, 'content': content})

        if util.get_entry(title):
            error = "Error. This entry already exists."
            return render(request, "encyclopedia/new_page.html", {'error': error, 'title': title, 'content': content})

        util.save_entry(title, content)
        # entry = util.get_entry(title)
        # html = markdown2.markdown(entry)

        return HttpResponseRedirect(reverse('encyclopedia:entry_page', args=[title]))

    return render(request, "encyclopedia/new_page.html")


def edit_page(request, entry):
    if request.method == 'POST':
        # print(request.POST)
        title = request.POST.get('title', '').strip()
        content = request.POST.get('content', '').strip()

        if not title or not content:
            error = "Error. Title and content are required fields."
            return render(request, "encyclopedia/edit_page.html", {'error': error, 'title': title, 'content': content})

        util.save_entry(title, content)

        return HttpResponseRedirect(reverse('encyclopedia:entry_page', args=[title]))

    title = entry
    content = util.get_entry(title)

    return render(request, "encyclopedia/edit_page.html", {'title': title, 'content': content})


def random_page(request):
    entries = util.list_entries()
    random_choice = random.choice(entries)

    return HttpResponseRedirect(reverse('encyclopedia:entry_page', args=[random_choice]))

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1>Edit page</h1>

    {% if error %}
        {{ error }}
    {% endif %}

    <form action="{% url 'encyclopedia:edit_page' title %}" method="post">
        {% csrf_token %}
        <div>
            <h4>
                <label for="title">Title</label>
            </h4>
                <input id="title" name="title" type="text" value="{{ title }}" required readonly>
        </div>
        <br>    
        <div>
            <h4>
                <label for="content">Content</label>
            </h4>
            <textarea id="content" name="content" required>{{ content }}</textarea>
        </div>

        <input type="submit" value="Save">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    {{ html|safe }}
    <a href="{% url 'encyclopedia:edit_page' entry %}">Edit Page</a>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href="{% url 'encyclopedia:entry_page' entry %}">
                <li>{{ entry }}</li>
            </a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    <!-- {% csrf_token %} -->
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1>Create new page</h1>

    {% if error %}
        {{ error }}
    {% endif %}

    <form action="{% url 'encyclopedia:new_page' %}" method="post">
        {% csrf_token %}
        <div>
            <h4>
                <label for="title">Title</label>
            </h4>
                <input id="title" name="title" type="text" value="{{ title }}" required>
        </div>
        <br>    
        <div>
            <h4>
                <label for="content">Content</label>
            </h4>
            <textarea id="content" name="content" value="{{ content }}" required></textarea>
        </div>

        <input type="submit" value="Save">
    </form>

    <script>
        document.getElementById("content").defaultValue = "{{ content }}";
    </script>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1> {{ number }} results for "<em>{{ q }}</em>" </h1>

    {% if results %}
        <ul>
            {% for result in results %}
                <a href="{% url 'encyclopedia:entry' result %}">
                    <li>{{ result }}</li>
                </a>
            {% endfor %}
        </ul> 
    {% endif %}

{% endblock %}